In [1]:
import pandas as pd
import numpy as np

career_skills = pd.read_csv("../data/career_skills.csv")

career_skills.head()

,Career,Python,SQL,Excel,Statistics,Data Analysis,Machine Learning,Deep Learning,NLP,Power BI,...,Java,JavaScript,HTML_CSS,C++,Git,Linux,Cloud,Cybersecurity,Communication,Problem Solving
0,Data Analyst,4,5,5,3,5,2,0,0,5,...,0,1,1,0,3,1,1,0,4,4
1,Data Scientist,5,4,2,5,5,5,4,3,2,...,0,1,1,0,3,2,2,0,4,5
2,ML Engineer,5,3,1,4,4,5,5,4,1,...,0,2,1,2,4,4,4,0,3,5
3,Software Developer,3,2,1,1,1,1,0,0,0,...,4,4,3,4,5,3,2,1,4,5
4,Web Developer,2,2,1,0,1,0,0,0,0,...,1,5,5,0,4,2,2,0,4,4

In [2]:
courses = pd.read_csv("../data/courses.csv")

courses.head()

,Course_ID,Course_Name,Platform,Skill,Level,Duration
0,C001,Python for Data Science,Online,Python,Beginner,8 weeks
1,C002,SQL for Data Analysis,Online,SQL,Beginner,6 weeks
2,C003,Statistics for Data Science,Online,Statistics,Intermediate,6 weeks
3,C004,Data Analysis with Python,Online,Data Analysis,Intermediate,8 weeks
4,C005,Machine Learning Specialization,Online,Machine Learning,Intermediate,12 weeks

In [3]:
career_skills.shape

(8, 21)

In [4]:
student_skills = {
    "Python": 4,
    "SQL": 3,
    "Excel": 4,
    "Statistics": 3,
    "Data Analysis": 4,
    "Machine Learning": 1,
    "Deep Learning": 0,
    "NLP": 0,
    "Power BI": 2,
    "Tableau": 2,
    "Java": 0,
    "JavaScript": 2,
    "HTML_CSS": 2,
    "C++": 1,
    "Git": 3,
    "Linux": 1,
    "Cloud": 0,
    "Cybersecurity": 0,
    "Communication": 4,
    "Problem Solving": 4
}

In [5]:
target_career = "Data Scientist"
career_row = career_skills[
    career_skills["Career"] == target_career
].iloc[0]

career_row

Career              Data Scientist
Python                           5
SQL                              4
Excel                            2
Statistics                       5
Data Analysis                    5
Machine Learning                 5
Deep Learning                    4
NLP                              3
Power BI                         2
Tableau                          2
Java                             0
JavaScript                       1
HTML_CSS                         1
C++                              0
Git                              3
Linux                            2
Cloud                            2
Cybersecurity                    0
Communication                    4
Problem Solving                  5
Name: 1, dtype: object

In [6]:
def calculate_skill_gap(student_skills, career_row):

    skill_gap = {}

    for skill in student_skills:
        required = career_row[skill]
        current = student_skills[skill]

        gap = required - current

        skill_gap[skill] = {
            "Current": current,
            "Required": required,
            "Gap": gap
        }

    return pd.DataFrame(skill_gap).T

In [7]:
gap_df = calculate_skill_gap(
    student_skills,
    career_row
)

gap_df

                  Current  Required  Gap
Python                  4         5    1
SQL                     3         4    1
Excel                   4         2   -2
Statistics              3         5    2
Data Analysis           4         5    1
Machine Learning        1         5    4
Deep Learning           0         4    4
NLP                     0         3    3
Power BI                2         2    0
Tableau                 2         2    0
Java                    0         0    0
JavaScript              2         1   -1
HTML_CSS                2         1   -1
C++                     1         0   -1
Git                     3         3    0
Linux                   1         2    1
Cloud                   0         2    2
Cybersecurity           0         0    0
Communication           4         4    0
Problem Solving         4         5    1

In [8]:
missing_skills = gap_df[
    gap_df["Gap"] > 0
].sort_values(
    by="Gap",
    ascending=False
)

missing_skills

                  Current  Required  Gap
Machine Learning        1         5    4
Deep Learning           0         4    4
NLP                     0         3    3
Statistics              3         5    2
Cloud                   0         2    2
Python                  4         5    1
SQL                     3         4    1
Data Analysis           4         5    1
Linux                   1         2    1
Problem Solving         4         5    1

In [9]:
def categorize_gap(gap):

    if gap >= 3:
        return "High Priority"

    elif gap == 2:
        return "Medium Priority"

    elif gap == 1:
        return "Low Priority"

    else:
        return "No Gap"

In [10]:
gap_df["Priority"] = gap_df["Gap"].apply(
    categorize_gap
)

gap_df

                  Current  Required  Gap         Priority
Python                  4         5    1     Low Priority
SQL                     3         4    1     Low Priority
Excel                   4         2   -2           No Gap
Statistics              3         5    2  Medium Priority
Data Analysis           4         5    1     Low Priority
Machine Learning        1         5    4    High Priority
Deep Learning           0         4    4    High Priority
NLP                     0         3    3    High Priority
Power BI                2         2    0           No Gap
Tableau                 2         2    0           No Gap
Java                    0         0    0           No Gap
JavaScript              2         1   -1           No Gap
HTML_CSS                2         1   -1           No Gap
C++                     1         0   -1           No Gap
Git                     3         3    0           No Gap
Linux                   1         2    1     Low Priority
Cloud                   0         2    2  Medium Priority
Cybersecurity           0         0    0           No Gap
Communication           4         4    0           No Gap
Problem Solving         4         5    1     Low Priority

In [11]:
strong_skills = gap_df[
    gap_df["Gap"] <= 0
].sort_values(
    by="Current",
    ascending=False
)

strong_skills

               Current  Required  Gap Priority
Excel                4         2   -2   No Gap
Communication        4         4    0   No Gap
Git                  3         3    0   No Gap
Power BI             2         2    0   No Gap
Tableau              2         2    0   No Gap
JavaScript           2         1   -1   No Gap
HTML_CSS             2         1   -1   No Gap
C++                  1         0   -1   No Gap
Java                 0         0    0   No Gap
Cybersecurity        0         0    0   No Gap

In [12]:
required_values = gap_df["Required"].replace(0, np.nan)
current_values = gap_df["Current"]

skill_percentages = (
    current_values / required_values
) * 100

skill_percentages = skill_percentages.clip(
    upper=100
)

readiness_score = skill_percentages.mean()

print(
    "Career Readiness Score:",
    round(readiness_score, 2)
)

Career Readiness Score: 67.35

In [13]:
print("================================")
print("       CAREERSENSE REPORT")
print("================================")

print("\nTarget Career:")
print(target_career)

print("\nCareer Readiness Score:")
print(round(readiness_score, 2), "%")

print("\nHigh Priority Skills:")
print(
    list(
        gap_df[
            gap_df["Priority"] == "High Priority"
        ].index
    )
)

print("\nMedium Priority Skills:")
print(
    list(
        gap_df[
            gap_df["Priority"] == "Medium Priority"
        ].index
    )
)

print("\nStrong Skills:")
print(
    list(
        gap_df[
            gap_df["Gap"] <= 0
        ].index
    )
)

================================
       CAREERSENSE REPORT
================================

Target Career:
Data Scientist

Career Readiness Score:
67.35 %

High Priority Skills:
['Machine Learning', 'Deep Learning', 'NLP']

Medium Priority Skills:
['Statistics', 'Cloud']

Strong Skills:
['Excel', 'Power BI', 'Tableau', 'Java', 'JavaScript', 'HTML_CSS', 'C++', 'Git', 'Cybersecurity', 'Communication']

In [14]:
courses.shape

(19, 6)

In [15]:
def recommend_courses(gap_df, courses):
    
    missing_skills = gap_df[
        gap_df["Gap"] > 0
    ].sort_values(
        by="Gap",
        ascending=False
    )
    
    recommendations = []
    
    for skill, row in missing_skills.iterrows():
        
        matching_courses = courses[
            courses["Skill"] == skill
        ]
        
        for _, course in matching_courses.iterrows():
            
            recommendations.append({
                "Skill": skill,
                "Gap": row["Gap"],
                "Priority": row["Priority"],
                "Course_ID": course["Course_ID"],
                "Course_Name": course["Course_Name"],
                "Platform": course["Platform"],
                "Level": course["Level"],
                "Duration": course["Duration"]
            })
    
    return pd.DataFrame(recommendations)

In [16]:
course_recommendations = recommend_courses(
    gap_df,
    courses
)

course_recommendations

,Skill,Gap,Priority,Course_ID,Course_Name,Platform,Level,Duration
0,Machine Learning,4,High Priority,C005,Machine Learning Specialization,Online,Intermediate,12 weeks
1,Deep Learning,4,High Priority,C006,Deep Learning Fundamentals,Online,Advanced,10 weeks
2,NLP,3,High Priority,C007,Natural Language Processing,Online,Advanced,8 weeks
3,Statistics,2,Medium Priority,C003,Statistics for Data Science,Online,Intermediate,6 weeks
4,Cloud,2,Medium Priority,C016,Cloud Computing Fundamentals,Online,Beginner,8 weeks
5,Python,1,Low Priority,C001,Python for Data Science,Online,Beginner,8 weeks
6,SQL,1,Low Priority,C002,SQL for Data Analysis,Online,Beginner,6 weeks
7,Data Analysis,1,Low Priority,C004,Data Analysis with Python,Online,Intermediate,8 weeks
8,Linux,1,Low Priority,C015,Linux Fundamentals,Online,Beginner,6 weeks
9,Problem Solving,1,Low Priority,C019,Problem Solving and Algorithms,Online,Intermediate,8 weeks

In [17]:
high_priority_courses = course_recommendations[
    course_recommendations["Priority"] == "High Priority"
]

high_priority_courses

,Skill,Gap,Priority,Course_ID,Course_Name,Platform,Level,Duration
0,Machine Learning,4,High Priority,C005,Machine Learning Specialization,Online,Intermediate,12 weeks
1,Deep Learning,4,High Priority,C006,Deep Learning Fundamentals,Online,Advanced,10 weeks
2,NLP,3,High Priority,C007,Natural Language Processing,Online,Advanced,8 weeks

In [18]:
top_courses = course_recommendations.head(5)

top_courses

,Skill,Gap,Priority,Course_ID,Course_Name,Platform,Level,Duration
0,Machine Learning,4,High Priority,C005,Machine Learning Specialization,Online,Intermediate,12 weeks
1,Deep Learning,4,High Priority,C006,Deep Learning Fundamentals,Online,Advanced,10 weeks
2,NLP,3,High Priority,C007,Natural Language Processing,Online,Advanced,8 weeks
3,Statistics,2,Medium Priority,C003,Statistics for Data Science,Online,Intermediate,6 weeks
4,Cloud,2,Medium Priority,C016,Cloud Computing Fundamentals,Online,Beginner,8 weeks

In [19]:
print("======================================")
print("       CAREERSENSE LEARNING PLAN")
print("======================================")

print("\nTarget Career:")
print(target_career)

print("\nCareer Readiness Score:")
print(round(readiness_score, 2), "%")

print("\nRecommended Courses:")
print("--------------------------------------")

for _, course in top_courses.iterrows():
    
    print(
        f"\nSkill: {course['Skill']}"
    )
    
    print(
        f"Priority: {course['Priority']}"
    )
    
    print(
        f"Course: {course['Course_Name']}"
    )
    
    print(
        f"Level: {course['Level']}"
    )
    
    print(
        f"Duration: {course['Duration']}"
    )

======================================
       CAREERSENSE LEARNING PLAN
======================================

Target Career:
Data Scientist

Career Readiness Score:
67.35 %

Recommended Courses:
--------------------------------------

Skill: Machine Learning
Priority: High Priority
Course: Machine Learning Specialization
Level: Intermediate
Duration: 12 weeks

Skill: Deep Learning
Priority: High Priority
Course: Deep Learning Fundamentals
Level: Advanced
Duration: 10 weeks

Skill: NLP
Priority: High Priority
Course: Natural Language Processing
Level: Advanced
Duration: 8 weeks

Skill: Statistics
Priority: Medium Priority
Course: Statistics for Data Science
Level: Intermediate
Duration: 6 weeks

Skill: Cloud
Priority: Medium Priority
Course: Cloud Computing Fundamentals
Level: Beginner
Duration: 8 weeks

In [20]:
target_career = "Data Analyst"

In [21]:
career_row = career_skills[
    career_skills["Career"] == target_career
].iloc[0]

gap_df = calculate_skill_gap(
    student_skills,
    career_row
)

gap_df["Priority"] = gap_df["Gap"].apply(
    categorize_gap
)

course_recommendations = recommend_courses(
    gap_df,
    courses
)

course_recommendations.head(10)

,Skill,Gap,Priority,Course_ID,Course_Name,Platform,Level,Duration
0,Power BI,3,High Priority,C008,Power BI for Data Analytics,Online,Beginner,6 weeks
1,Tableau,2,Medium Priority,C009,Tableau for Data Visualization,Online,Beginner,6 weeks
2,SQL,2,Medium Priority,C002,SQL for Data Analysis,Online,Beginner,6 weeks
3,Data Analysis,1,Low Priority,C004,Data Analysis with Python,Online,Intermediate,8 weeks
4,Machine Learning,1,Low Priority,C005,Machine Learning Specialization,Online,Intermediate,12 weeks
5,Cloud,1,Low Priority,C016,Cloud Computing Fundamentals,Online,Beginner,8 weeks