In [1]:
import pandas as pd
import numpy as np

career_skills = pd.read_csv("career_skills.csv")

career_skills.head()

,Career,Python,SQL,Excel,Statistics,Data Analysis,Machine Learning,Deep Learning,NLP,Power BI,...,Java,JavaScript,HTML_CSS,C++,Git,Linux,Cloud,Cybersecurity,Communication,Problem Solving
0,Data Analyst,4,5,5,3,5,2,0,0,5,...,0,1,1,0,3,1,1,0,4,4
1,Data Scientist,5,4,2,5,5,5,4,3,2,...,0,1,1,0,3,2,2,0,4,5
2,ML Engineer,5,3,1,4,4,5,5,4,1,...,0,2,1,2,4,4,4,0,3,5
3,Software Developer,3,2,1,1,1,1,0,0,0,...,4,4,3,4,5,3,2,1,4,5
4,Web Developer,2,2,1,0,1,0,0,0,0,...,1,5,5,0,4,2,2,0,4,4

In [2]:
career_skills.shape

(8, 21)

In [3]:
student_skills = {
    "Python": 4,
    "SQL": 3,
    "Excel": 4,
    "Statistics": 3,
    "Data Analysis": 4,
    "Machine Learning": 1,
    "Deep Learning": 0,
    "NLP": 0,
    "Power BI": 2,
    "Tableau": 2,
    "Java": 0,
    "JavaScript": 2,
    "HTML_CSS": 2,
    "C++": 1,
    "Git": 3,
    "Linux": 1,
    "Cloud": 0,
    "Cybersecurity": 0,
    "Communication": 4,
    "Problem Solving": 4
}

In [4]:
target_career = "Data Scientist"
career_row = career_skills[
    career_skills["Career"] == target_career
].iloc[0]

career_row

Career              Data Scientist
Python                           5
SQL                              4
Excel                            2
Statistics                       5
Data Analysis                    5
Machine Learning                 5
Deep Learning                    4
NLP                              3
Power BI                         2
Tableau                          2
Java                             0
JavaScript                       1
HTML_CSS                         1
C++                              0
Git                              3
Linux                            2
Cloud                            2
Cybersecurity                    0
Communication                    4
Problem Solving                  5
Name: 1, dtype: object

In [5]:
def calculate_skill_gap(student_skills, career_row):

    skill_gap = {}

    for skill in student_skills:
        required = career_row[skill]
        current = student_skills[skill]

        gap = required - current

        skill_gap[skill] = {
            "Current": current,
            "Required": required,
            "Gap": gap
        }

    return pd.DataFrame(skill_gap).T

In [6]:
gap_df = calculate_skill_gap(
    student_skills,
    career_row
)

gap_df

                  Current  Required  Gap
Python                  4         5    1
SQL                     3         4    1
Excel                   4         2   -2
Statistics              3         5    2
Data Analysis           4         5    1
Machine Learning        1         5    4
Deep Learning           0         4    4
NLP                     0         3    3
Power BI                2         2    0
Tableau                 2         2    0
Java                    0         0    0
JavaScript              2         1   -1
HTML_CSS                2         1   -1
C++                     1         0   -1
Git                     3         3    0
Linux                   1         2    1
Cloud                   0         2    2
Cybersecurity           0         0    0
Communication           4         4    0
Problem Solving         4         5    1

In [7]:
missing_skills = gap_df[
    gap_df["Gap"] > 0
].sort_values(
    by="Gap",
    ascending=False
)

missing_skills

                  Current  Required  Gap
Machine Learning        1         5    4
Deep Learning           0         4    4
NLP                     0         3    3
Statistics              3         5    2
Cloud                   0         2    2
Python                  4         5    1
SQL                     3         4    1
Data Analysis           4         5    1
Linux                   1         2    1
Problem Solving         4         5    1

In [8]:
def categorize_gap(gap):

    if gap >= 3:
        return "High Priority"

    elif gap == 2:
        return "Medium Priority"

    elif gap == 1:
        return "Low Priority"

    else:
        return "No Gap"

In [9]:
gap_df["Priority"] = gap_df["Gap"].apply(
    categorize_gap
)

gap_df

                  Current  Required  Gap         Priority
Python                  4         5    1     Low Priority
SQL                     3         4    1     Low Priority
Excel                   4         2   -2           No Gap
Statistics              3         5    2  Medium Priority
Data Analysis           4         5    1     Low Priority
Machine Learning        1         5    4    High Priority
Deep Learning           0         4    4    High Priority
NLP                     0         3    3    High Priority
Power BI                2         2    0           No Gap
Tableau                 2         2    0           No Gap
Java                    0         0    0           No Gap
JavaScript              2         1   -1           No Gap
HTML_CSS                2         1   -1           No Gap
C++                     1         0   -1           No Gap
Git                     3         3    0           No Gap
Linux                   1         2    1     Low Priority
Cloud                   0         2    2  Medium Priority
Cybersecurity           0         0    0           No Gap
Communication           4         4    0           No Gap
Problem Solving         4         5    1     Low Priority

In [10]:
strong_skills = gap_df[
    gap_df["Gap"] <= 0
].sort_values(
    by="Current",
    ascending=False
)

strong_skills

               Current  Required  Gap Priority
Excel                4         2   -2   No Gap
Communication        4         4    0   No Gap
Git                  3         3    0   No Gap
Power BI             2         2    0   No Gap
Tableau              2         2    0   No Gap
JavaScript           2         1   -1   No Gap
HTML_CSS             2         1   -1   No Gap
C++                  1         0   -1   No Gap
Java                 0         0    0   No Gap
Cybersecurity        0         0    0   No Gap

In [11]:
required_values = gap_df["Required"].replace(0, np.nan)
current_values = gap_df["Current"]

skill_percentages = (
    current_values / required_values
) * 100

skill_percentages = skill_percentages.clip(
    upper=100
)

readiness_score = skill_percentages.mean()

print(
    "Career Readiness Score:",
    round(readiness_score, 2)
)

Career Readiness Score: 67.35

In [12]:
print("================================")
print("       CAREERSENSE REPORT")
print("================================")

print("\nTarget Career:")
print(target_career)

print("\nCareer Readiness Score:")
print(round(readiness_score, 2), "%")

print("\nHigh Priority Skills:")
print(
    list(
        gap_df[
            gap_df["Priority"] == "High Priority"
        ].index
    )
)

print("\nMedium Priority Skills:")
print(
    list(
        gap_df[
            gap_df["Priority"] == "Medium Priority"
        ].index
    )
)

print("\nStrong Skills:")
print(
    list(
        gap_df[
            gap_df["Gap"] <= 0
        ].index
    )
)

================================
       CAREERSENSE REPORT
================================

Target Career:
Data Scientist

Career Readiness Score:
67.35 %

High Priority Skills:
['Machine Learning', 'Deep Learning', 'NLP']

Medium Priority Skills:
['Statistics', 'Cloud']

Strong Skills:
['Excel', 'Power BI', 'Tableau', 'Java', 'JavaScript', 'HTML_CSS', 'C++', 'Git', 'Cybersecurity', 'Communication']